# Generated by Django 5.1.3 — OPAL Update 131.7 R146
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("academics", "0010_delete_academicyear_alter_subject_options_and_more"),
        ("students", "0011_student_photo_size_limit"),
    ]

    operations = [
        migrations.CreateModel(
            name="StudentNote",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("role", models.CharField(choices=[("management", "ملاحظة الإدارة"), ("homeroom", "ملاحظة مربي الصف"), ("subject", "ملاحظة معلم المادة")], max_length=20, verbose_name="نوع الملاحظة")),
                ("content", models.TextField(max_length=2000, verbose_name="الملاحظة")),
                ("created_at", models.DateTimeField(auto_now_add=True, verbose_name="تاريخ التسجيل")),
                ("updated_at", models.DateTimeField(auto_now=True, verbose_name="آخر تعديل")),
                ("author", models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name="student_notes", to=settings.AUTH_USER_MODEL, verbose_name="كاتب الملاحظة")),
                ("student", models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name="school_notes", to="students.student", verbose_name="الطالب")),
                ("subject", models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name="student_notes", to="academics.subject", verbose_name="المادة")),
            ],
            options={
                "ordering": ["-created_at", "-pk"],
                "indexes": [
                    models.Index(fields=["student", "role", "created_at"], name="st_note_stu_role_created_idx"),
                    models.Index(fields=["author", "created_at"], name="st_note_author_created_idx"),
                ],
            },
        ),
    ]
